// React JS/Introduction Cards/src/NavBar.jsx
export function NavBar(){
    return(
        <>
            <nav className="navbar">
                <div className="container-fluid">
                    <a className="navbar-brand" href="https://reactjs.org/" target="_blank" rel="noreferrer">JSX</a>
                    <form className="d-flex" role="search">
                        <input className="form-control me-2" type="search" placeholder="Search" aria-label="Search" />
                        <button className="btn btn-dark" type="submit">Search</button>
                    </form>
                </div>
            </nav>
        </>
    )
}

// Angular/Resume Cards/src/app/nav-bar/nav-bar.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-nav-bar',
  templateUrl: './nav-bar.component.html',
  styleUrls: ['./nav-bar.component.css']
})
export class NavBarComponent implements OnInit {

  constructor() { }
  
  ngOnInit(): void {
  }
  WebName = 'Angular Project'
}

<nav class="navbar sticky-top" style="background-color: #415b54">
    <div class="container-fluid">
      <a class="navbar-brand" style="color: white;">
        {{WebName}}
      </a>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" style="color: white;" type="submit">Search</button>
      </form>
    </div>
  </nav>
