// Angular/Introduction Cards/src/app/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }
  brand = "NG||TS"
}

<nav class="navbar">
    <div class="container-fluid">
        <a class="navbar-brand" href="https://angular.io/" target="_blank" rel="noreferrer">{{brand}}</a>
        <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" />
            <button class="btn btn-dark" type="submit">Search</button>
        </form>
    </div>
</nav>

// React JS/Introduction Cards/src/NavBar.jsx
export function NavBar(){
    return(
        <>
            <nav className="navbar">
                <div className="container-fluid">
                    <a className="navbar-brand" href="https://reactjs.org/" target="_blank" rel="noreferrer">JSX</a>
                    <form className="d-flex" role="search">
                        <input className="form-control me-2" type="search" placeholder="Search" aria-label="Search" />
                        <button className="btn btn-dark" type="submit">Search</button>
                    </form>
                </div>
            </nav>
        </>
    )
}
